export const ErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  API_KEY_MISSING: 'API_KEY_MISSING',
  API_KEY_INVALID: 'API_KEY_INVALID',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  /** SDK chat blocked by plan / rate limits (end-user friendly message in `message`). */
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  BAD_GATEWAY: 'BAD_GATEWAY',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_USER_DATA: 'INVALID_USER_DATA',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
  GOOGLE_NOT_CONFIGURED: 'GOOGLE_NOT_CONFIGURED',
  INVALID_OTP: 'INVALID_OTP',
  DELETE_ACCOUNT_BLOCKED: 'DELETE_ACCOUNT_BLOCKED',
  TEAM_MEMBER_NOT_FOUND: 'TEAM_MEMBER_NOT_FOUND',
  CANNOT_REMOVE_SELF: 'CANNOT_REMOVE_SELF',
  CANNOT_REMOVE_ADMIN: 'CANNOT_REMOVE_ADMIN',
  SEAT_SELF_DELETE_BLOCKED: 'SEAT_SELF_DELETE_BLOCKED',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  NO_ACTIVE_SUBSCRIPTION: 'NO_ACTIVE_SUBSCRIPTION',
  SUBSCRIPTION_UPDATE_ERROR: 'SUBSCRIPTION_UPDATE_ERROR',
  SUBSCRIPTION_CANCEL_ERROR: 'SUBSCRIPTION_CANCEL_ERROR',
  CHECKOUT_CREATION_FAILED: 'CHECKOUT_CREATION_FAILED',
  BILLING_NOT_CONFIGURED: 'BILLING_NOT_CONFIGURED',
  TRIAL_NOT_ELIGIBLE: 'TRIAL_NOT_ELIGIBLE',
  /** Studio workspace project cap reached — see `details.limit`. */
  PROJECT_LIMIT_REACHED: 'PROJECT_LIMIT_REACHED',
  /** Studio workspace team seat cap reached — see `details.limit`. */
  SEAT_LIMIT_REACHED: 'SEAT_LIMIT_REACHED',
  /** Studio project action cap reached — see `details.limit`. */
  ACTION_LIMIT_REACHED: 'ACTION_LIMIT_REACHED',
  /** Shared demo login is held by another visitor — see `details.retryAfterSeconds`. */
  TEST_ACCOUNT_IN_USE: 'TEST_ACCOUNT_IN_USE',
  /** Demo session lease expired — sign in again or pick another account. */
  TEST_ACCOUNT_LEASE_EXPIRED: 'TEST_ACCOUNT_LEASE_EXPIRED',
  /** Studio report submission cooldown — see `details.retryAfterSeconds`. */
  REPORT_RATE_LIMIT: 'REPORT_RATE_LIMIT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Fallback when the response body has no `errorCode`. */
export const HttpStatusToErrorCode: Record<number, ErrorCode> = {
  400: ErrorCode.VALIDATION_ERROR,
  401: ErrorCode.UNAUTHORIZED,
  403: ErrorCode.FORBIDDEN,
  404: ErrorCode.NOT_FOUND,
  405: ErrorCode.METHOD_NOT_ALLOWED,
  409: ErrorCode.CONFLICT,
  422: ErrorCode.VALIDATION_ERROR,
  429: ErrorCode.QUOTA_EXCEEDED,
  500: ErrorCode.INTERNAL_ERROR,
  501: ErrorCode.NOT_IMPLEMENTED,
  502: ErrorCode.BAD_GATEWAY,
  503: ErrorCode.SERVICE_UNAVAILABLE,
  504: ErrorCode.GATEWAY_TIMEOUT,
};
